# generated
name: x7vgqyqqmgg
on:
  workflow_dispatch: {}
  workflow_call:
    inputs:
      xyqag4m6lzm:
        type: string
        required: true
    secrets:
      x2tog4huplt:
        required: true
      x62mffq6fec:
        required: true
      xaqnb4spokw:
        required: true
      xbucws5r6z7:
        required: true
      xfvt4ipssxd:
        required: true
      xhnuatecbvz:
        required: true
      xhzquij5vjz:
        required: true
      xkxmguw6k42:
        required: true
      xkz7gzyz75s:
        required: true
      xquqiaiupja:
        required: true
      xrecw4v2j5j:
        required: true
      xwfcb4ka6lh:
        required: true
      xzeifyyht7x:
        required: true
permissions: {}
jobs:
  xdnpb52ii3q:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    outputs:
      x2yfivsezh6: ${{ steps.run.outputs.x2yfivsezh6 }}
      x32o4475kwd: ${{ steps.run.outputs.x32o4475kwd }}
      x7cadbeahdd: ${{ steps.run.outputs.x7cadbeahdd }}
      xbolddyuwpe: ${{ steps.run.outputs.xbolddyuwpe }}
      xfikslxuqog: ${{ steps.run.outputs.xfikslxuqog }}
      xh54fra5cva: ${{ steps.run.outputs.xh54fra5cva }}
      xnmxyv36ybd: ${{ steps.run.outputs.xnmxyv36ybd }}
      xraejei5dgh: ${{ steps.run.outputs.xraejei5dgh }}
      xraqfe7cyrm: ${{ steps.run.outputs.xraqfe7cyrm }}
      xzxym3ak7pm: ${{ steps.run.outputs.xzxym3ak7pm }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          xkv56qn5iuh: ${{ secrets.xrecw4v2j5j }}
          xfgmwg3xnad: ${{ secrets.xaqnb4spokw }}
          xj5q6er6gr3: ${{ secrets.xkz7gzyz75s }}
          x4ncggu5esz: xnrtohzayvy
          x3umuxxylao: x2yfivsezh6,x32o4475kwd,x7cadbeahdd,xbolddyuwpe,xfikslxuqog,xh54fra5cva,xnmxyv36ybd,xraejei5dgh,xraqfe7cyrm,xzxym3ak7pm
          xyqag4m6lzm: ${{ inputs.xyqag4m6lzm }}
          xobosfmqwfr: ${{ secrets.xquqiaiupja }}
          xgofw2krbdr: ${{ secrets.xzeifyyht7x }}
          xwbqojknqft: ${{ secrets.xbucws5r6z7 }}
          xsp4ozekw7v: ${{ secrets.xhzquij5vjz }}
        run: ./.github/bin/x7vgqyqqmgg
  xnylbixrcua:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    needs:
      - xdnpb52ii3q
    outputs:
      xnhq2bg3o22: ${{ steps.run.outputs.xnhq2bg3o22 }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          xkv56qn5iuh: ${{ secrets.xrecw4v2j5j }}
          xfgmwg3xnad: ${{ secrets.xaqnb4spokw }}
          xj5q6er6gr3: ${{ secrets.xkz7gzyz75s }}
          x4ncggu5esz: x6ye5eqsbxx
          x3umuxxylao: xnhq2bg3o22
          xdx5oxzjovn: ${{ needs.xdnpb52ii3q.outputs.x7cadbeahdd }}
          xevtw47feoc: ${{ needs.xdnpb52ii3q.outputs.xbolddyuwpe }}
          xl2il5l3cow: ${{ needs.xdnpb52ii3q.outputs.xfikslxuqog }}
          xruvb7f3dwy: ${{ needs.xdnpb52ii3q.outputs.x32o4475kwd }}
          xukreijpwi3: ${{ needs.xdnpb52ii3q.outputs.xraejei5dgh }}
          xsls4vz6c23: ${{ secrets.x2tog4huplt }}
          xobosfmqwfr: ${{ secrets.xquqiaiupja }}
          xgofw2krbdr: ${{ secrets.xzeifyyht7x }}
          xwbqojknqft: ${{ secrets.xbucws5r6z7 }}
          xsp4ozekw7v: ${{ secrets.xhzquij5vjz }}
          xhhlauipgb7: ${{ secrets.x62mffq6fec }}
          x6brkfjpq3q: ${{ secrets.xhnuatecbvz }}
          xdjvub5rkan: ${{ secrets.xwfcb4ka6lh }}
        run: ./.github/bin/x7vgqyqqmgg
  xx6fg63vjuu:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    needs:
      - xdnpb52ii3q
    outputs:
      xrqxrnj4jf5: ${{ steps.run.outputs.xrqxrnj4jf5 }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          xkv56qn5iuh: ${{ secrets.xrecw4v2j5j }}
          xfgmwg3xnad: ${{ secrets.xaqnb4spokw }}
          xj5q6er6gr3: ${{ secrets.xkz7gzyz75s }}
          x4ncggu5esz: x3b6okgvd3l
          x3umuxxylao: xrqxrnj4jf5
          xdldbxpzqhf: ${{ needs.xdnpb52ii3q.outputs.x32o4475kwd }}
          xncwotsuncn: ${{ needs.xdnpb52ii3q.outputs.xfikslxuqog }}
          xviibzeysxn: ${{ needs.xdnpb52ii3q.outputs.x7cadbeahdd }}
          xwr6e3otq4b: ${{ needs.xdnpb52ii3q.outputs.xraejei5dgh }}
          xyuhphvmed2: ${{ needs.xdnpb52ii3q.outputs.xbolddyuwpe }}
          xsls4vz6c23: ${{ secrets.x2tog4huplt }}
          xobosfmqwfr: ${{ secrets.xquqiaiupja }}
          xgofw2krbdr: ${{ secrets.xzeifyyht7x }}
          xwbqojknqft: ${{ secrets.xbucws5r6z7 }}
          xsp4ozekw7v: ${{ secrets.xhzquij5vjz }}
          xhhlauipgb7: ${{ secrets.x62mffq6fec }}
          x6brkfjpq3q: ${{ secrets.xhnuatecbvz }}
          xdjvub5rkan: ${{ secrets.xwfcb4ka6lh }}
        run: ./.github/bin/x7vgqyqqmgg
  xsvkhiclodw:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    needs:
      - xdnpb52ii3q
    outputs:
      x3jbfklpdlx: ${{ steps.run.outputs.x3jbfklpdlx }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          xkv56qn5iuh: ${{ secrets.xrecw4v2j5j }}
          xfgmwg3xnad: ${{ secrets.xaqnb4spokw }}
          xj5q6er6gr3: ${{ secrets.xkz7gzyz75s }}
          x4ncggu5esz: xzsaxutbtot
          x3umuxxylao: x3jbfklpdlx
          x2nkrsmxbff: ${{ needs.xdnpb52ii3q.outputs.xraejei5dgh }}
          xrmvlvmydpz: ${{ needs.xdnpb52ii3q.outputs.x32o4475kwd }}
          xypdsgdojfy: ${{ needs.xdnpb52ii3q.outputs.xbolddyuwpe }}
          xzee7c3k3kg: ${{ needs.xdnpb52ii3q.outputs.x7cadbeahdd }}
          xzxolx6j6ep: ${{ needs.xdnpb52ii3q.outputs.xfikslxuqog }}
          xsls4vz6c23: ${{ secrets.x2tog4huplt }}
          xobosfmqwfr: ${{ secrets.xquqiaiupja }}
          xgofw2krbdr: ${{ secrets.xzeifyyht7x }}
          xwbqojknqft: ${{ secrets.xbucws5r6z7 }}
          xsp4ozekw7v: ${{ secrets.xhzquij5vjz }}
          xhhlauipgb7: ${{ secrets.x62mffq6fec }}
          x6brkfjpq3q: ${{ secrets.xhnuatecbvz }}
          xdjvub5rkan: ${{ secrets.xwfcb4ka6lh }}
        run: ./.github/bin/x7vgqyqqmgg
  x5gueq6uoid:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    needs:
      - xdnpb52ii3q
    outputs:
      xygfqj3cr37: ${{ steps.run.outputs.xygfqj3cr37 }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          xkv56qn5iuh: ${{ secrets.xrecw4v2j5j }}
          xfgmwg3xnad: ${{ secrets.xaqnb4spokw }}
          xj5q6er6gr3: ${{ secrets.xkz7gzyz75s }}
          x4ncggu5esz: xqni5ienbee
          x3umuxxylao: xygfqj3cr37
          x6v5kwoj4lq: ${{ needs.xdnpb52ii3q.outputs.xzxym3ak7pm }}
          xjzw6ffeb4k: ${{ needs.xdnpb52ii3q.outputs.xnmxyv36ybd }}
          xkth6lgj7mm: ${{ needs.xdnpb52ii3q.outputs.xh54fra5cva }}
          xm5d5x3mvty: ${{ needs.xdnpb52ii3q.outputs.xraqfe7cyrm }}
          xmmke4zaa4h: ${{ needs.xdnpb52ii3q.outputs.x7cadbeahdd }}
          xpi4yhg5z2i: ${{ needs.xdnpb52ii3q.outputs.x32o4475kwd }}
          xqsp5obzws5: ${{ needs.xdnpb52ii3q.outputs.x2yfivsezh6 }}
          xtfpn5xfotq: ${{ needs.xdnpb52ii3q.outputs.xfikslxuqog }}
          xwhjw6zzzsn: ${{ needs.xdnpb52ii3q.outputs.xbolddyuwpe }}
          x6cpa5i37um: ${{ secrets.xkxmguw6k42 }}
          xsherm2qqpm: ${{ secrets.xfvt4ipssxd }}
          xsls4vz6c23: ${{ secrets.x2tog4huplt }}
          xobosfmqwfr: ${{ secrets.xquqiaiupja }}
          xgofw2krbdr: ${{ secrets.xzeifyyht7x }}
          xwbqojknqft: ${{ secrets.xbucws5r6z7 }}
          xsp4ozekw7v: ${{ secrets.xhzquij5vjz }}
          xhhlauipgb7: ${{ secrets.x62mffq6fec }}
          x6brkfjpq3q: ${{ secrets.xhnuatecbvz }}
          xdjvub5rkan: ${{ secrets.xwfcb4ka6lh }}
        run: ./.github/bin/x7vgqyqqmgg
  xvfvxxlopnd:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    needs:
      - xdnpb52ii3q
    outputs:
      x5l6pqggkrc: ${{ steps.run.outputs.x5l6pqggkrc }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          xkv56qn5iuh: ${{ secrets.xrecw4v2j5j }}
          xfgmwg3xnad: ${{ secrets.xaqnb4spokw }}
          xj5q6er6gr3: ${{ secrets.xkz7gzyz75s }}
          x4ncggu5esz: x7eyzfpra5z
          x3umuxxylao: x5l6pqggkrc
          x2to2c2xqis: ${{ needs.xdnpb52ii3q.outputs.x2yfivsezh6 }}
          xflwgem4zw4: ${{ needs.xdnpb52ii3q.outputs.xnmxyv36ybd }}
          xjdwydw5t2i: ${{ needs.xdnpb52ii3q.outputs.xh54fra5cva }}
          xjmf3qli5jl: ${{ needs.xdnpb52ii3q.outputs.xfikslxuqog }}
          xmln54re3kf: ${{ needs.xdnpb52ii3q.outputs.x32o4475kwd }}
          xqaj3lwt6vf: ${{ needs.xdnpb52ii3q.outputs.xzxym3ak7pm }}
          xrdmaj4uj2j: ${{ needs.xdnpb52ii3q.outputs.xraqfe7cyrm }}
          xsjphoz74e5: ${{ needs.xdnpb52ii3q.outputs.xbolddyuwpe }}
          xueu7javcgz: ${{ needs.xdnpb52ii3q.outputs.x7cadbeahdd }}
          x6cpa5i37um: ${{ secrets.xkxmguw6k42 }}
          xsherm2qqpm: ${{ secrets.xfvt4ipssxd }}
          xsls4vz6c23: ${{ secrets.x2tog4huplt }}
          xobosfmqwfr: ${{ secrets.xquqiaiupja }}
          xgofw2krbdr: ${{ secrets.xzeifyyht7x }}
          xwbqojknqft: ${{ secrets.xbucws5r6z7 }}
          xsp4ozekw7v: ${{ secrets.xhzquij5vjz }}
          xhhlauipgb7: ${{ secrets.x62mffq6fec }}
          x6brkfjpq3q: ${{ secrets.xhnuatecbvz }}
          xdjvub5rkan: ${{ secrets.xwfcb4ka6lh }}
        run: ./.github/bin/x7vgqyqqmgg
  xtbwo76au6f:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    needs:
      - xdnpb52ii3q
    outputs:
      x7pqgijfmvh: ${{ steps.run.outputs.x7pqgijfmvh }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          xkv56qn5iuh: ${{ secrets.xrecw4v2j5j }}
          xfgmwg3xnad: ${{ secrets.xaqnb4spokw }}
          xj5q6er6gr3: ${{ secrets.xkz7gzyz75s }}
          x4ncggu5esz: xlprxtb7vh3
          x3umuxxylao: x7pqgijfmvh
          x3l575n4iu7: ${{ needs.xdnpb52ii3q.outputs.xh54fra5cva }}
          x464rwabiy2: ${{ needs.xdnpb52ii3q.outputs.xbolddyuwpe }}
          x6i2v3einsh: ${{ needs.xdnpb52ii3q.outputs.x32o4475kwd }}
          xfqzp663dtp: ${{ needs.xdnpb52ii3q.outputs.x7cadbeahdd }}
          xk24j3disym: ${{ needs.xdnpb52ii3q.outputs.xraqfe7cyrm }}
          xkle7falvwi: ${{ needs.xdnpb52ii3q.outputs.xzxym3ak7pm }}
          xlatqbmcwzm: ${{ needs.xdnpb52ii3q.outputs.xfikslxuqog }}
          xn5iacfzoju: ${{ needs.xdnpb52ii3q.outputs.x2yfivsezh6 }}
          xuhvmtlakmr: ${{ needs.xdnpb52ii3q.outputs.xnmxyv36ybd }}
          x6cpa5i37um: ${{ secrets.xkxmguw6k42 }}
          xsherm2qqpm: ${{ secrets.xfvt4ipssxd }}
          xsls4vz6c23: ${{ secrets.x2tog4huplt }}
          xobosfmqwfr: ${{ secrets.xquqiaiupja }}
          xgofw2krbdr: ${{ secrets.xzeifyyht7x }}
          xwbqojknqft: ${{ secrets.xbucws5r6z7 }}
          xsp4ozekw7v: ${{ secrets.xhzquij5vjz }}
          xhhlauipgb7: ${{ secrets.x62mffq6fec }}
          x6brkfjpq3q: ${{ secrets.xhnuatecbvz }}
          xdjvub5rkan: ${{ secrets.xwfcb4ka6lh }}
        run: ./.github/bin/x7vgqyqqmgg
  xctqwf2intl:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    needs:
      - xdnpb52ii3q
      - xnylbixrcua
      - xx6fg63vjuu
      - xsvkhiclodw
      - x5gueq6uoid
      - xvfvxxlopnd
      - xtbwo76au6f
    outputs:
      xgnwqxfffzu: ${{ steps.run.outputs.xgnwqxfffzu }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          xkv56qn5iuh: ${{ secrets.xrecw4v2j5j }}
          xfgmwg3xnad: ${{ secrets.xaqnb4spokw }}
          xj5q6er6gr3: ${{ secrets.xkz7gzyz75s }}
          x4ncggu5esz: xfqpzms5pec
          x3umuxxylao: xgnwqxfffzu
          x6ugn2jhqbw: ${{ needs.xvfvxxlopnd.outputs.x5l6pqggkrc }}
          xb7i3f66dtf: ${{ needs.xtbwo76au6f.outputs.x7pqgijfmvh }}
          xehc7uldgom: ${{ needs.x5gueq6uoid.outputs.xygfqj3cr37 }}
          xknsdfrfjhi: ${{ needs.xsvkhiclodw.outputs.x3jbfklpdlx }}
          xkuiptwc44q: ${{ needs.xnylbixrcua.outputs.xnhq2bg3o22 }}
          xnrtsq33c2u: ${{ needs.xx6fg63vjuu.outputs.xrqxrnj4jf5 }}
          xvbjx3bksgg: ${{ needs.xdnpb52ii3q.outputs.x7cadbeahdd }}
          xsls4vz6c23: ${{ secrets.x2tog4huplt }}
          xobosfmqwfr: ${{ secrets.xquqiaiupja }}
          xgofw2krbdr: ${{ secrets.xzeifyyht7x }}
          xwbqojknqft: ${{ secrets.xbucws5r6z7 }}
          xsp4ozekw7v: ${{ secrets.xhzquij5vjz }}
          xhhlauipgb7: ${{ secrets.x62mffq6fec }}
          x6brkfjpq3q: ${{ secrets.xhnuatecbvz }}
          xdjvub5rkan: ${{ secrets.xwfcb4ka6lh }}
        run: ./.github/bin/x7vgqyqqmgg
