# generated
name: xn72mhxitdo
on:
  workflow_dispatch: {}
  workflow_call:
    inputs:
      xjzinrhqbga:
        type: string
        required: true
    secrets:
      x2tog4huplt:
        required: true
      x62mffq6fec:
        required: true
      xaqnb4spokw:
        required: true
      xbucws5r6z7:
        required: true
      xfvt4ipssxd:
        required: true
      xhnuatecbvz:
        required: true
      xhzquij5vjz:
        required: true
      xkxmguw6k42:
        required: true
      xkz7gzyz75s:
        required: true
      xquqiaiupja:
        required: true
      xrecw4v2j5j:
        required: true
      xwfcb4ka6lh:
        required: true
      xzeifyyht7x:
        required: true
permissions: {}
jobs:
  x6zijawd7aq:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    outputs:
      x37gvxeepxb: ${{ steps.run.outputs.x37gvxeepxb }}
      x7p5bqwbqoy: ${{ steps.run.outputs.x7p5bqwbqoy }}
      x7zjeohsiq6: ${{ steps.run.outputs.x7zjeohsiq6 }}
      xcxa74wxyl6: ${{ steps.run.outputs.xcxa74wxyl6 }}
      xfjscxu7kgu: ${{ steps.run.outputs.xfjscxu7kgu }}
      xh66wxhoa5t: ${{ steps.run.outputs.xh66wxhoa5t }}
      xrquefbqiwy: ${{ steps.run.outputs.xrquefbqiwy }}
      xtxeik4xzsj: ${{ steps.run.outputs.xtxeik4xzsj }}
      xy5fvz7zsai: ${{ steps.run.outputs.xy5fvz7zsai }}
      xyjggxlwelx: ${{ steps.run.outputs.xyjggxlwelx }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          xohrqcke2n7: ${{ secrets.xrecw4v2j5j }}
          xxpsc5boeen: ${{ secrets.xaqnb4spokw }}
          xxrfnn6a7dz: ${{ secrets.xkz7gzyz75s }}
          xvcsjc4ta2a: xuhpmaghiou
          xfwdum6tmqt: x37gvxeepxb,x7p5bqwbqoy,x7zjeohsiq6,xcxa74wxyl6,xfjscxu7kgu,xh66wxhoa5t,xrquefbqiwy,xtxeik4xzsj,xy5fvz7zsai,xyjggxlwelx
          xjzinrhqbga: ${{ inputs.xjzinrhqbga }}
          xgg253safiu: ${{ secrets.xquqiaiupja }}
          xh2wagiy5mm: ${{ secrets.xzeifyyht7x }}
          xcglfmxeayd: ${{ secrets.xbucws5r6z7 }}
          xcdxoqdgak7: ${{ secrets.xhzquij5vjz }}
        run: ./.github/bin/xn72mhxitdo
  xqnjxqwylvq:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    needs:
      - x6zijawd7aq
    outputs:
      x4dcmuxtlks: ${{ steps.run.outputs.x4dcmuxtlks }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          xohrqcke2n7: ${{ secrets.xrecw4v2j5j }}
          xxpsc5boeen: ${{ secrets.xaqnb4spokw }}
          xxrfnn6a7dz: ${{ secrets.xkz7gzyz75s }}
          xvcsjc4ta2a: xkoerv3wan2
          xfwdum6tmqt: x4dcmuxtlks
          x34keos4qyj: ${{ needs.x6zijawd7aq.outputs.xcxa74wxyl6 }}
          xjlam3ztppz: ${{ needs.x6zijawd7aq.outputs.xrquefbqiwy }}
          xp6fkylkdpv: ${{ needs.x6zijawd7aq.outputs.xy5fvz7zsai }}
          xxbpis42wfe: ${{ needs.x6zijawd7aq.outputs.xh66wxhoa5t }}
          xxuqt725l5m: ${{ needs.x6zijawd7aq.outputs.xyjggxlwelx }}
          xyoicw6m4b2: ${{ secrets.x2tog4huplt }}
          xgg253safiu: ${{ secrets.xquqiaiupja }}
          xh2wagiy5mm: ${{ secrets.xzeifyyht7x }}
          xcglfmxeayd: ${{ secrets.xbucws5r6z7 }}
          xcdxoqdgak7: ${{ secrets.xhzquij5vjz }}
          xr4n5opdn2e: ${{ secrets.x62mffq6fec }}
          xlr52uoa76c: ${{ secrets.xhnuatecbvz }}
          xfwoi6sn3y3: ${{ secrets.xwfcb4ka6lh }}
        run: ./.github/bin/xn72mhxitdo
  xobzehraatt:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    needs:
      - x6zijawd7aq
    outputs:
      xg62s6oykr6: ${{ steps.run.outputs.xg62s6oykr6 }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          xohrqcke2n7: ${{ secrets.xrecw4v2j5j }}
          xxpsc5boeen: ${{ secrets.xaqnb4spokw }}
          xxrfnn6a7dz: ${{ secrets.xkz7gzyz75s }}
          xvcsjc4ta2a: x7gnaruhirh
          xfwdum6tmqt: xg62s6oykr6
          xfe35fzptiu: ${{ needs.x6zijawd7aq.outputs.xcxa74wxyl6 }}
          xl2i36577rl: ${{ needs.x6zijawd7aq.outputs.xyjggxlwelx }}
          xlwa65jqfkf: ${{ needs.x6zijawd7aq.outputs.xh66wxhoa5t }}
          xtibcf5wi4h: ${{ needs.x6zijawd7aq.outputs.xrquefbqiwy }}
          xve4ctehx2y: ${{ needs.x6zijawd7aq.outputs.xy5fvz7zsai }}
          xyoicw6m4b2: ${{ secrets.x2tog4huplt }}
          xgg253safiu: ${{ secrets.xquqiaiupja }}
          xh2wagiy5mm: ${{ secrets.xzeifyyht7x }}
          xcglfmxeayd: ${{ secrets.xbucws5r6z7 }}
          xcdxoqdgak7: ${{ secrets.xhzquij5vjz }}
          xr4n5opdn2e: ${{ secrets.x62mffq6fec }}
          xlr52uoa76c: ${{ secrets.xhnuatecbvz }}
          xfwoi6sn3y3: ${{ secrets.xwfcb4ka6lh }}
        run: ./.github/bin/xn72mhxitdo
  xhoin6ryvu3:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    needs:
      - x6zijawd7aq
    outputs:
      xykh3l4l2zq: ${{ steps.run.outputs.xykh3l4l2zq }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          xohrqcke2n7: ${{ secrets.xrecw4v2j5j }}
          xxpsc5boeen: ${{ secrets.xaqnb4spokw }}
          xxrfnn6a7dz: ${{ secrets.xkz7gzyz75s }}
          xvcsjc4ta2a: xjyrmpqdj4d
          xfwdum6tmqt: xykh3l4l2zq
          x2vulomw7h5: ${{ needs.x6zijawd7aq.outputs.xcxa74wxyl6 }}
          x7upfff7f6y: ${{ needs.x6zijawd7aq.outputs.xyjggxlwelx }}
          xkwlcrkp4pt: ${{ needs.x6zijawd7aq.outputs.xy5fvz7zsai }}
          xlhjtcljgnr: ${{ needs.x6zijawd7aq.outputs.xrquefbqiwy }}
          xwayxpvzbfs: ${{ needs.x6zijawd7aq.outputs.xh66wxhoa5t }}
          xyoicw6m4b2: ${{ secrets.x2tog4huplt }}
          xgg253safiu: ${{ secrets.xquqiaiupja }}
          xh2wagiy5mm: ${{ secrets.xzeifyyht7x }}
          xcglfmxeayd: ${{ secrets.xbucws5r6z7 }}
          xcdxoqdgak7: ${{ secrets.xhzquij5vjz }}
          xr4n5opdn2e: ${{ secrets.x62mffq6fec }}
          xlr52uoa76c: ${{ secrets.xhnuatecbvz }}
          xfwoi6sn3y3: ${{ secrets.xwfcb4ka6lh }}
        run: ./.github/bin/xn72mhxitdo
  xdvdd7bxhn6:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    needs:
      - x6zijawd7aq
    outputs:
      xhrh3s3j77o: ${{ steps.run.outputs.xhrh3s3j77o }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          xohrqcke2n7: ${{ secrets.xrecw4v2j5j }}
          xxpsc5boeen: ${{ secrets.xaqnb4spokw }}
          xxrfnn6a7dz: ${{ secrets.xkz7gzyz75s }}
          xvcsjc4ta2a: xm6r7iccoer
          xfwdum6tmqt: xhrh3s3j77o
          x6vfwpir4bm: ${{ needs.x6zijawd7aq.outputs.x7p5bqwbqoy }}
          x7a57qnwigm: ${{ needs.x6zijawd7aq.outputs.xfjscxu7kgu }}
          xbuppatq6is: ${{ needs.x6zijawd7aq.outputs.x37gvxeepxb }}
          xdtyhhhh6fy: ${{ needs.x6zijawd7aq.outputs.xrquefbqiwy }}
          xeg7nhzvmcq: ${{ needs.x6zijawd7aq.outputs.xcxa74wxyl6 }}
          xfnemxn623n: ${{ needs.x6zijawd7aq.outputs.xyjggxlwelx }}
          xtb27cb4mdn: ${{ needs.x6zijawd7aq.outputs.xtxeik4xzsj }}
          xzhzpz4aivz: ${{ needs.x6zijawd7aq.outputs.x7zjeohsiq6 }}
          xzzuivubrnc: ${{ needs.x6zijawd7aq.outputs.xy5fvz7zsai }}
          xic3aeerr4n: ${{ secrets.xkxmguw6k42 }}
          x3qbcuugg4p: ${{ secrets.xfvt4ipssxd }}
          xyoicw6m4b2: ${{ secrets.x2tog4huplt }}
          xgg253safiu: ${{ secrets.xquqiaiupja }}
          xh2wagiy5mm: ${{ secrets.xzeifyyht7x }}
          xcglfmxeayd: ${{ secrets.xbucws5r6z7 }}
          xcdxoqdgak7: ${{ secrets.xhzquij5vjz }}
          xr4n5opdn2e: ${{ secrets.x62mffq6fec }}
          xlr52uoa76c: ${{ secrets.xhnuatecbvz }}
          xfwoi6sn3y3: ${{ secrets.xwfcb4ka6lh }}
        run: ./.github/bin/xn72mhxitdo
  xrwexolkecb:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    needs:
      - x6zijawd7aq
    outputs:
      xqhfdsqfqre: ${{ steps.run.outputs.xqhfdsqfqre }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          xohrqcke2n7: ${{ secrets.xrecw4v2j5j }}
          xxpsc5boeen: ${{ secrets.xaqnb4spokw }}
          xxrfnn6a7dz: ${{ secrets.xkz7gzyz75s }}
          xvcsjc4ta2a: xyngmp5ugjn
          xfwdum6tmqt: xqhfdsqfqre
          x6bthus2vuj: ${{ needs.x6zijawd7aq.outputs.xrquefbqiwy }}
          x6r3e3yvl4e: ${{ needs.x6zijawd7aq.outputs.x7zjeohsiq6 }}
          xaqxkhoclxx: ${{ needs.x6zijawd7aq.outputs.xy5fvz7zsai }}
          xdr6oodridv: ${{ needs.x6zijawd7aq.outputs.x7p5bqwbqoy }}
          xl5moen4njm: ${{ needs.x6zijawd7aq.outputs.xfjscxu7kgu }}
          xnmw5syyz6j: ${{ needs.x6zijawd7aq.outputs.x37gvxeepxb }}
          xpoovlj4mca: ${{ needs.x6zijawd7aq.outputs.xcxa74wxyl6 }}
          xrfl57rwns3: ${{ needs.x6zijawd7aq.outputs.xtxeik4xzsj }}
          xwzpxtjxgkh: ${{ needs.x6zijawd7aq.outputs.xyjggxlwelx }}
          xic3aeerr4n: ${{ secrets.xkxmguw6k42 }}
          x3qbcuugg4p: ${{ secrets.xfvt4ipssxd }}
          xyoicw6m4b2: ${{ secrets.x2tog4huplt }}
          xgg253safiu: ${{ secrets.xquqiaiupja }}
          xh2wagiy5mm: ${{ secrets.xzeifyyht7x }}
          xcglfmxeayd: ${{ secrets.xbucws5r6z7 }}
          xcdxoqdgak7: ${{ secrets.xhzquij5vjz }}
          xr4n5opdn2e: ${{ secrets.x62mffq6fec }}
          xlr52uoa76c: ${{ secrets.xhnuatecbvz }}
          xfwoi6sn3y3: ${{ secrets.xwfcb4ka6lh }}
        run: ./.github/bin/xn72mhxitdo
  xe5lmip252o:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    needs:
      - x6zijawd7aq
    outputs:
      xcmof4qyho5: ${{ steps.run.outputs.xcmof4qyho5 }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          xohrqcke2n7: ${{ secrets.xrecw4v2j5j }}
          xxpsc5boeen: ${{ secrets.xaqnb4spokw }}
          xxrfnn6a7dz: ${{ secrets.xkz7gzyz75s }}
          xvcsjc4ta2a: xa5pb4sjycm
          xfwdum6tmqt: xcmof4qyho5
          x4tbq6dvizt: ${{ needs.x6zijawd7aq.outputs.xyjggxlwelx }}
          x5iona6a3ch: ${{ needs.x6zijawd7aq.outputs.x7zjeohsiq6 }}
          x7hx7jp3h7v: ${{ needs.x6zijawd7aq.outputs.xcxa74wxyl6 }}
          xgvplcb7hql: ${{ needs.x6zijawd7aq.outputs.xfjscxu7kgu }}
          xjglwpd2mkw: ${{ needs.x6zijawd7aq.outputs.xrquefbqiwy }}
          xn5txjqjoge: ${{ needs.x6zijawd7aq.outputs.xtxeik4xzsj }}
          xnjvylhbtkr: ${{ needs.x6zijawd7aq.outputs.xy5fvz7zsai }}
          xvdsimdin2a: ${{ needs.x6zijawd7aq.outputs.x37gvxeepxb }}
          xytoeulshid: ${{ needs.x6zijawd7aq.outputs.x7p5bqwbqoy }}
          xic3aeerr4n: ${{ secrets.xkxmguw6k42 }}
          x3qbcuugg4p: ${{ secrets.xfvt4ipssxd }}
          xyoicw6m4b2: ${{ secrets.x2tog4huplt }}
          xgg253safiu: ${{ secrets.xquqiaiupja }}
          xh2wagiy5mm: ${{ secrets.xzeifyyht7x }}
          xcglfmxeayd: ${{ secrets.xbucws5r6z7 }}
          xcdxoqdgak7: ${{ secrets.xhzquij5vjz }}
          xr4n5opdn2e: ${{ secrets.x62mffq6fec }}
          xlr52uoa76c: ${{ secrets.xhnuatecbvz }}
          xfwoi6sn3y3: ${{ secrets.xwfcb4ka6lh }}
        run: ./.github/bin/xn72mhxitdo
  xe7aeqf2e6h:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    needs:
      - x6zijawd7aq
      - xqnjxqwylvq
      - xobzehraatt
      - xhoin6ryvu3
      - xdvdd7bxhn6
      - xrwexolkecb
      - xe5lmip252o
    outputs:
      xfz5d3ge7p4: ${{ steps.run.outputs.xfz5d3ge7p4 }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          xohrqcke2n7: ${{ secrets.xrecw4v2j5j }}
          xxpsc5boeen: ${{ secrets.xaqnb4spokw }}
          xxrfnn6a7dz: ${{ secrets.xkz7gzyz75s }}
          xvcsjc4ta2a: x3zp3omwkak
          xfwdum6tmqt: xfz5d3ge7p4
          xgawdfzactf: ${{ needs.xrwexolkecb.outputs.xqhfdsqfqre }}
          xhhkb2nbyll: ${{ needs.xhoin6ryvu3.outputs.xykh3l4l2zq }}
          xjn3cnuhjm4: ${{ needs.xobzehraatt.outputs.xg62s6oykr6 }}
          xlojcvd6yyh: ${{ needs.xqnjxqwylvq.outputs.x4dcmuxtlks }}
          xpqmf75qffg: ${{ needs.xdvdd7bxhn6.outputs.xhrh3s3j77o }}
          xunkdfkjraj: ${{ needs.x6zijawd7aq.outputs.xy5fvz7zsai }}
          xysqxpqrjlg: ${{ needs.xe5lmip252o.outputs.xcmof4qyho5 }}
          xyoicw6m4b2: ${{ secrets.x2tog4huplt }}
          xgg253safiu: ${{ secrets.xquqiaiupja }}
          xh2wagiy5mm: ${{ secrets.xzeifyyht7x }}
          xcglfmxeayd: ${{ secrets.xbucws5r6z7 }}
          xcdxoqdgak7: ${{ secrets.xhzquij5vjz }}
          xr4n5opdn2e: ${{ secrets.x62mffq6fec }}
          xlr52uoa76c: ${{ secrets.xhnuatecbvz }}
          xfwoi6sn3y3: ${{ secrets.xwfcb4ka6lh }}
        run: ./.github/bin/xn72mhxitdo
